os: linux
arch: s390x
distro: bionic

before_script:
  - python script.py

jobs:
  include:
    - stage: Check PR
      if: branch = main AND type = pull_request
      script: 
        - echo "Current PR number $TRAVIS_PULL_REQUEST"
        - curl https://api.github.com/repos/Rohan-Shinde-98/test-pr-files/pulls/${TRAVIS_PULL_REQUEST}/files
