--- 
arch: ppc64le
distro: bionic
os: linux

env:
  global:
    TRAVIS_DEBUG_MODE=true

jobs: 
  include: 
    - 
      if: "branch = main AND type = pull_request"
      script: 
        - "python3 script.py $TRAVIS_PULL_REQUEST"
        - "python3 createBuilds.py"
